# Generated by Django 5.2.4 on 2025-07-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_choice',
            field=models.CharField(blank=True, help_text='Nom du fichier avatar choisi parmi les prédéfinis', max_length=100, null=True),
        ),
    ]
